name: drifts-and-complexity
channels:
  - conda-forge
dependencies:
  # Python
  - python=3.10
  - pip
  - numpy=1.24.*
  - pandas=1.5.*
  - scipy=1.10.*
  - scikit-learn=1.2.*
  - networkx=3.0
  - matplotlib=3.6.*
  - seaborn=0.12.*
  - tqdm=4.64.*
  - pytz=2022.7.*
  - pyyaml
  - lxml
  - graphviz
  - python-graphviz


  # PM4Py (pip-only)
  - pip:
      - pm4py==2.4.1
      - pulp==3.2.1
      - Wasserstein==1.1.0
      - strsimpy==0.2.1
      - Levenshtein==0.21.0
      - BitVector
      - lempel_ziv_complexity
      - mypy
      - python-Levenshtein
